# Generated by Django 4.0.1 on 2022-01-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
